### ISSUE TITLE
Name "Fast Search" 

### ISSUE THREAD

**Issue by benthebear** [palasthotel/wordpress-solr#24]
@EdwardBock The Name "Fast Search" might be a teeny tiny biiit complicated as there is a major norwegian Search Company which is named "Fast", and which is now a part of Microsoft …

https://en.wikipedia.org/wiki/Fast_Search_%26_Transfer

… we should consider renaming the plugin …

**Comment by EdwardBock** [comment]
@benthebear Do you have any proposals?

Thing is: We can rename the plugin. But we will never be able to change the plugins url https://wordpress.org/plugins/fast-search-powered-by-solr/

**Comment by benthebear** [comment]
Never mind the URL.

Some suggestions …

* better search
* nice search
* advanced <del>dungeons and dragons</del> search and find
* fast find
* scholar search
* panda search
* aurelius search

**Comment by EdwardBock** [comment]
Hmmm I  like *better search*

**Comment by benthebear** [comment]
I linky "sunny search" the most …

**Comment by EdwardBock** [comment]
This would have been my second best. So I would say we take that one ;)

**Comment by EdwardBock** [comment]
- [ ] Rename Plugin to "Sunny seach"

**Comment by EdwardBock** [comment]
It is renamed!
