### ISSUE TITLE
Sorry, something went wrong. Okok, but what? :)

### ISSUE THREAD

**Issue by trueqap** [palasthotel/wordpress-solr#25]
Hello,

Thanks for the plugin. 

I got this error message. Do you have any idea? 

`Fatal error: Uncaught Solarium\Exception\HttpException: Solr HTTP error: OK (400) {"error":{"msg":"sort param field can't be found: ds_published","code":400}} in /usr/www/users/trueqx/hotel/teszt/wp-content/plugins/fast-search-powered-by-solr/lib/solarium/solarium/library/Solarium/Core/Query/Result/Result.php:103 Stack trace: #0 /usr/www/users/trueqx/hotel/teszt/wp-content/plugins/fast-search-powered-by-solr/lib/solarium/solarium/library/Solarium/Core/Client/Client.php(736): Solarium\Core\Query\Result\Result->__construct(Object(Solarium\Client), Object(Solarium\QueryType\Select\Query\Query), Object(Solarium\Core\Client\Response)) #1 /usr/www/users/trueqx/hotel/teszt/wp-content/plugins/fast-search-powered-by-solr/lib/solarium/solarium/library/Solarium/Core/Client/Client.php(767): Solarium\Core\Client\Client->createResult(Object(Solarium\QueryType\Select\Query\Query), Object(Solarium\Core\Client\Response)) #2 /usr/www/users/trueqx/hotel/teszt/wp-content/plugins/fast-search-powered-by-solr/lib/solarium/solarium/library/Sola in /usr/www/users/trueqx/hotel/teszt/wp-content/plugins/fast-search-powered-by-solr/lib/solarium/solarium/library/Solarium/Core/Query/Result/Result.php on line 103`

**Comment by trueqap** [comment]
The Update index is not working: Sorry, something went wrong.

**Comment by EdwardBock** [comment]
Hi @trueqap 

that seems to be an solr configuration issue.

Please use the provided schema and config XMLs.

https://github.com/palasthotel/wordpress-solr/blob/master/solr-config/schema.xml  
https://github.com/palasthotel/wordpress-solr/blob/master/solr-config/solrconfig.xml

That should fix your problem.
