### ISSUE TITLE
Add option on all Post-Types to not index the Post

### ISSUE THREAD

**Issue by benthebear** [palasthotel/wordpress-solr#27]
In order to do so, we need to …

1. Add Admin-Box with Checkbox to ignore Post on Index
2. Store it as a flag / post_meta
3. Add it as a negative criteria here … https://github.com/palasthotel/wordpress-solr/blob/master/inc/posts.php#L66

**Comment by benthebear** [comment]
@EdwardBock could you speed up this tast a bit, please, pretty please?

**Comment by EdwardBock** [comment]
@benthebear 

There is a way to ignore posts:

https://github.com/palasthotel/wordpress-solr/blob/master/inc/index-runner.php#L64-L68

Use filter ```solr_post_ignore``` and return true

https://github.com/palasthotel/wordpress-solr/blob/master/solr.php#L48

**Comment by EdwardBock** [comment]
@benthebear 

Comes with 1.0.2
