### ISSUE TITLE
Add new Filter the_content_solr

### ISSUE THREAD

**Issue by benthebear** [palasthotel/wordpress-solr#28]
@EdwardBock Could you please add a Filter the_content_solr here, after …

https://github.com/palasthotel/wordpress-solr/blob/master/inc/solr-index/solr-post-fields.php#L54

… in between Line 54 and 55. 

Thank you so much!

**Comment by EdwardBock** [comment]
@benthebear 

Please use ```solr_add_post_fields_to_document``` to manipulate the document.

https://github.com/palasthotel/wordpress-solr/blob/master/inc/solr-index/solr-post-fields.php#L80

**Comment by EdwardBock** [comment]
@benthebear 

Or use filter ```solr_add_fields_post``` to filter document.

https://github.com/palasthotel/wordpress-solr/blob/master/solr.php#L46

**Comment by benthebear** [comment]
Feinifein!
